version: "2.1"
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.0.0

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - git clone https://github.com/XavierSamuelHuppe/3w5-h22-tp2-backend-test1
      - run: npm install
      - run: npm run test
  integrateFrontend:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run: git clone https://github.com/XavierSamuelHuppe/3w5-h22-tp2-backend-test1
      - run: git clone https://github.com/XavierSamuelHuppe/3w5-h22-tp2-frontend-test1
      - run: cd 3w5-h22-tp2-frontend-test1 && npm install
      - run: cd 3w5-h22-tp2-frontend-test1 && npm run build
      - run: mkdir 3w5-h22-tp2-backend-test1/public
      - run: cp -r 3w5-h22-tp2-frontend-test1/build/* 3w5-h22-tp2-backend-test1/public
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - .
workflows:
  build:
    jobs:
      - checkoutAndTest
      - integrateFrontend:
          requires:
            - checkoutAndTest
      - eb/deploy:
          application-name: xavier3-app
          environment-name: xavier3-app-dev
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - integrateFrontend
