version: "2.1"
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.0.0

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run: git clone https://github.com/XavierSamuelHuppe/3w5-h22-tp2-backend-test1
      - run: cd 3w5-h22-tp2-backend-test1 && npm install
      - run: cd 3w5-h22-tp2-backend-test1 && npm run test
  integrateFrontend:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run: git clone https://github.com/XavierSamuelHuppe/3w5-h22-tp2-backend-test1
      - run: git clone https://github.com/XavierSamuelHuppe/3w5-h22-tp2-frontend-test1
      - run: cd 3w5-h22-tp2-frontend-test1 && npm install
      - run: cd 3w5-h22-tp2-frontend-test1 && npm run build
      - run: mkdir 3w5-h22-tp2-backend-test1/public
      - run: cp -rT 3w5-h22-tp2-frontend-test1/build 3w5-h22-tp2-backend-test1/public
      - persist_to_workspace:
          root: .
          paths:
            - 3w5-h22-tp2-backend-test1
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: .
      - eb/setup
      - run: cd 3w5-h22-tp2-backend-test1 && eb init xavier3-app -r $AWS_DEFAULT_REGION -p node.js
      - run: cd 3w5-h22-tp2-backend-test1/public && ls -al
      - run: cd 3w5-h22-tp2-backend-test1/public && cat .env
      - run: cd 3w5-h22-tp2-backend-test1 && eb deploy xavier3-app-dev
      - run: cd 3w5-h22-tp2-backend-test1 && eb status

workflows:
  build:
    jobs:
      - checkoutAndTest
      - integrateFrontend:
          requires:
            - checkoutAndTest
      - deploy:
          requires:
            - integrateFrontend
