version: "2.1"
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.0.0

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  integrateFrontend:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run: git clone https://github.com/XavierSamuelHuppe/3w5-h22-tp2-backend
      - run: git clone https://github.com/XavierSamuelHuppe/3w5-h22-tp2-frontend
      - run: cd 3w5-h22-tp2-frontend && npm install
      - run: cd 3w5-h22-tp2-frontend && npm run build
      - run: mkdir 3w5-h22-tp2-backend/public
      - run: cp -r 3w5-h22-tp2-frontend/build/* 3w5-h22-tp2-backend/public
      - run: cd 3w5-h22-tp2-backend/public && ls -al
      - eb/setup
workflows:
  build:
    jobs:
      - checkoutAndTest
      - integrateFrontend:
          requires:
            - checkoutAndTest
      - eb/deploy:
          application-name: xavier3-app
          environment-name: xavier3-app-dev
          app-dir: 3w5-h22-tp2-backend
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - integrateFrontend
